baseURL = "https://pwnagotchi.ai/"
languageCode = "en-us"
title = "Pwnagotchi - Deep Reinforcement Learning instrumenting bettercap for WiFi pwning."

theme = "hugo-theme-learn"
# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
unsafe= true

[params]
themeVariant = "yellow"
disableShortcutsTitle=true
# editURL = "https://github.com/evilsocket/www.pwnagotchi.ai/edit/master/content/"
disableBreadcrumb = true
disableNextPrev = true


[[menu.shortcuts]]
name = "<br/><img src='https://img.shields.io/twitter/follow/pwnagotchi?style=social&logo=twitter' alt='follow on Twitter'>"
url = "https://twitter.com/intent/follow?screen_name=pwnagotchi"
weight = 1

[[menu.shortcuts]]
name = '<img alt="Discourse posts" src="https://img.shields.io/discourse/posts?server=https%3A%2F%2Fcommunity.pwnagotchi.ai%2F&style=flat-square">'
url = "https://community.pwnagotchi.ai/"
weight = 1.5

# [[menu.shortcuts]]
# name = "<img alt='Slack' src='https://invite.pwnagotchi.ai/badge.svg'>"
# url = "https://invite.pwnagotchi.ai/"
# weight = 2

[[menu.shortcuts]]
name = '<img alt="Software License" src="https://img.shields.io/badge/license-GPL3-brightgreen.svg?style=flat-square">'
url = "https://github.com/evilsocket/pwnagotchi/blob/master/LICENSE.md"
weight = 3

[[menu.shortcuts]] 
name = '<img alt="Travis" src="https://img.shields.io/travis/evilsocket/pwnagotchi/master.svg?style=flat-square">'
url = "https://travis-ci.org/evilsocket/pwnagotchi"
weight = 4

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> pwnagotchi"
url = "https://github.com/evilsocket/pwnagotchi"
weight = 5

[[menu.shortcuts]]
name = "<i class='fab fa-reddit'></i> r/pwnagotchi"
url = "https://www.reddit.com/r/pwnagotchi/"
weight = 6
